Tests implemented for FederationGatewayConfig
linnea-bonnevier/cwa-server pull request #7
Opened 2021-02-22 15:08 UTC by linnea-bonnevier

4 tests implemented

2021-02-22 15:09 UTC, linnea-bonnevier commented
@hallon-heyman Could you please test them for me? Since I cannot run it on my computer

2021-02-22 16:38 UTC, Atema requested changes

2021-02-22 16:38 UTC, Atema commented on common/federation/src/test/java/app/coronawarn/server/common/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java
> +    assertThat(ssl.getBaseUrl().isNotNull());
You have the closing paranthenses at the wrong place here; it should be `assertThat(ssl.getBaseUrl()).isNotNull()`

2021-02-22 16:38 UTC, Atema commented on common/federation/src/test/java/app/coronawarn/server/common/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java
> +import jdk.jfr.Timestamp;
This shouldn't be here

2021-02-22 16:44 UTC, Atema commented on common/federation/src/test/java/app/coronawarn/server/common/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java
> +    assertThat(ssl.getCertificateType(),is("PKCS12"));
Instead of using `assertThat(x, is("y"))`, this projects tends to use `assertThat(x).isEqualTo("y")`

2021-02-23 09:05 UTC, Atema commented
Looks good now. I'll test if it works and then merge in a minute

2021-02-23 09:12 UTC, Atema commented
I get some error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
8.1:testCompile (default-testCompile) on project federation: Compilation failure
: Compilation failure:
[ERROR] /root/cwa-server/common/federation/src/test/java/app/coronawarn/server/c
ommon/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java:[50
,8] cannot find symbol
[ERROR]   symbol:   method setBaseUrl(java.lang.String)
[ERROR]   location: variable ssl of type app.coronawarn.server.common.federation.client.config.FederationGatewayConfig.Ssl
[ERROR] /root/cwa-server/common/federation/src/test/java/app/coronawarn/server/common/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java:[51,19] cannot find symbol
[ERROR]   symbol:   method getBaseUrl()
[ERROR]   location: variable ssl of type app.coronawarn.server.common.federation.client.config.FederationGatewayConfig.Ssl
```

2021-02-23 09:20 UTC, linnea-bonnevier commented
> I get some error:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
> 8.1:testCompile (default-testCompile) on project federation: Compilation failure
> : Compilation failure:
> [ERROR] /root/cwa-server/common/federation/src/test/java/app/coronawarn/server/c
> ommon/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java:[50
> ,8] cannot find symbol
> [ERROR]   symbol:   method setBaseUrl(java.lang.String)
> [ERROR]   location: variable ssl of type app.coronawarn.server.common.federation.client.config.FederationGatewayConfig.Ssl
> [ERROR] /root/cwa-server/common/federation/src/test/java/app/coronawarn/server/common/federation/client/CloudFederationFeignHttpClientProviderSmokeTest.java:[51,19] cannot find symbol
> [ERROR]   symbol:   method getBaseUrl()
> [ERROR]   location: variable ssl of type app.coronawarn.server.common.federation.client.config.FederationGatewayConfig.Ssl
> ```

I'll look into it, thanks for running it

2021-02-23 09:50 UTC, linnea-bonnevier commented
Okay I think I fixed the problem

2021-02-23 09:50 UTC, Atema commented
I'll check

2021-02-23 10:09 UTC, Atema approved these changes
Runs fine now, and the tests pass.

2021-02-23 10:10 UTC, merged